### ISSUE TITLE
meshio for mesh i/o?

### ISSUE THREAD

**Issue by nschloe** [pypr/pysph#100]
The author of [meshio](https://github.com/nschloe/meshio) here.

I noticed there's quite a bit of code in https://github.com/pypr/pysph/blob/master/pysph/tools/gmsh.py dealing with I/O for gmsh and vtk meshes. Much of this can probably be replaced by a meshio one-liner. Just a suggestion.

**Comment by prabhuramachandran** [comment]
Thanks @nschloe.  That is a great suggestion and I'll see if we can do this at some point and remove any old code like this.  Right now there is a lot of other churn on the pysph code that I need to worry about.  That module was written on a flight before I was aware of meshio (perhaps before meshio existed!)...

**Comment by prabhuramachandran** [comment]
Meshio is an optional dependency and we do use it a bit now, closing this for now.
