### ISSUE TITLE
where to find ami.sh or starcluster directory

### ISSUE THREAD

**Issue by tamuanand** [pypr/pysph#161]
Hi

I am having trouble locating the ami.sh and/or the starcluster directory when I set up a EC2 instance from the AMI ID ami-01fdc27a as suggested here: https://pysph.readthedocs.io/en/latest/starcluster/overview.html

I could not find the PySPH repository or a Starcluster directory in my Ubuntu instance, 

I then did a 
`pip install PySPH `

and then tried to look around for the StarCluster directory but could not find it either.

Am I missing something here?

Thanks in advance,
Anand

**Comment by prabhuramachandran** [comment]
When you pip install, it installs the packages into the Python environment so you can import and use the modules.  If you want the other files like the startcluster related ones, you will need to clone the git repository or grab a zip file from here https://github.com/pypr/pysph/zipball/master
The files are in the `starcluster` directory

HTH.
