### ISSUE TITLE
Error when running pysph test

### ISSUE THREAD

**Issue by alda30** [pypr/pysph#251]
Hi, I am new to pysph and installed it on my Ubuntu 18.04.
When I run "pysph test", I get the following error:

`====================================== test session starts =======================================
platform linux -- Python 3.6.9, pytest-5.4.1, py-1.8.1, pluggy-0.13.1
rootdir: /home/ehsan/gpusph
collected 242 items / 26 errors / 216 selected                                                   

============================================= ERRORS =============================================
_______________________ ERROR collecting base/tests/test_device_helper.py ________________________
ImportError while importing test module '/home/ehsan/.local/lib/python3.6/site-packages/pysph/base/tests/test_device_helper.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../.local/lib/python3.6/site-packages/pysph/base/tests/test_device_helper.py:4: in <module>
    from pysph.base.utils import get_particle_array  # noqa: E402
../.local/lib/python3.6/site-packages/pysph/base/utils.py:7: in <module>
    from .particle_array import ParticleArray, \
pysph/base/particle_array.pyx:25: in init pysph.base.particle_array
    ???
../.local/lib/python3.6/site-packages/pysph/base/device_helper.py:12: in <module>
    from compyle.template import Template
E   ModuleNotFoundError: No module named 'compyle.template'
_______________________ ERROR collecting base/tests/test_domain_manager.py _______________________
ImportError while importing test module '/home/ehsan/.local/lib/python3.6/site-packages/pysph/base/tests/test_domain_manager.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../.local/lib/python3.6/site-packages/pysph/base/tests/test_domain_manager.py:8: in <module>
    from pysph.base.nnps import DomainManager, BoxSortNNPS, LinkedListNNPS
../.local/lib/python3.6/site-packages/pysph/base/nnps.py:1: in <module>
    from pysph.base.nnps_base import get_number_of_threads, py_flatten, \
pysph/base/particle_array.pxd:33: in init pysph.base.nnps_base
    ???
pysph/base/particle_array.pyx:25: in init pysph.base.particle_array
    ???
../.local/lib/python3.6/site-packages/pysph/base/device_helper.py:12: in <module>
    from compyle.template import Template
E   ModuleNotFoundError: No module named 'compyle.template'
_______________________ ERROR collecting base/tests/test_neighbor_cache.py _______________________
../.local/lib/python3.6/site-packages/pysph/base/tests/test_neighbor_cache.py:7: in <module>
    from pysph.base.nnps import NeighborCache, LinkedListNNPS
../.local/lib/python3.6/site-packages/pysph/base/nnps.py:1: in <module>
    from pysph.base.nnps_base import get_number_of_threads, py_flatten, \
pysph/base/nnps_base.pyx:218: in init pysph.base.nnps_base
    ???
E   AttributeError: type object 'pysph.base.nnps_base.NNPSParticleArrayWrapper' has no attribute '__reduce_cython__'
____________________________ ERROR collecting base/tests/test_nnps.py ____________________________
ImportError while importing test module '/home/ehsan/.local/lib/python3.6/site-packages/pysph/base/tests/test_nnps.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../.local/lib/python3.6/site-packages/pysph/base/tests/test_nnps.py:12: in <module>
    from pysph.base.utils import get_particle_array
../.local/lib/python3.6/site-packages/pysph/base/utils.py:7: in <module>
    from .particle_array import ParticleArray, \
pysph/base/particle_array.pyx:25: in init pysph.base.particle_array
    ???
../.local/lib/python3.6/site-packages/pysph/base/device_helper.py:12: in <module>
    from compyle.template import Template
E   ModuleNotFoundError: No module named 'compyle.template'
___________________________ ERROR collecting base/tests/test_octree.py ___________________________
ImportError while importing test module '/home/ehsan/.local/lib/python3.6/site-packages/pysph/base/tests/test_octree.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../.local/lib/python3.6/site-packages/pysph/base/tests/test_octree.py:10: in <module>
    from pysph.base.utils import get_particle_array
../.local/lib/python3.6/site-packages/pysph/base/utils.py:7: in <module>
    from .particle_array import ParticleArray, \
pysph/base/particle_array.pyx:25: in init pysph.base.particle_array
    ???
../.local/lib/python3.6/site-packages/pysph/base/device_helper.py:12: in <module>
    from compyle.template import Template
E   ModuleNotFoundError: No module named 'compyle.template'
_______________________ ERROR collecting base/tests/test_particle_array.py _______________________
ImportError while importing test module '/home/ehsan/.local/lib/python3.6/site-packages/pysph/base/tests/test_particle_array.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../.local/lib/python3.6/site-packages/pysph/base/tests/test_particle_array.py:10: in <module>
    from pysph.base import particle_array
pysph/base/particle_array.pyx:25: in init pysph.base.particle_array
    ???
../.local/lib/python3.6/site-packages/pysph/base/device_helper.py:12: in <module>
    from compyle.template import Template
E   ModuleNotFoundError: No module named 'compyle.template'
_______________________ ERROR collecting base/tests/test_periodic_nnps.py ________________________
../.local/lib/python3.6/site-packages/pysph/base/tests/test_periodic_nnps.py:7: in <module>
    from pysph.base.nnps import DomainManager, BoxSortNNPS, LinkedListNNPS, \
../.local/lib/python3.6/site-packages/pysph/base/nnps.py:1: in <module>
    from pysph.base.nnps_base import get_number_of_threads, py_flatten, \
pysph/base/nnps_base.pyx:218: in init pysph.base.nnps_base
    ???
E   AttributeError: type object 'pysph.base.nnps_base.NNPSParticleArrayWrapper' has no attribute '__reduce_cython__'
___________________________ ERROR collecting base/tests/test_utils.py ____________________________
ImportError while importing test module '/home/ehsan/.local/lib/python3.6/site-packages/pysph/base/tests/test_utils.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../.local/lib/python3.6/site-packages/pysph/base/tests/test_utils.py:3: in <module>
    from ..utils import is_overloaded_method
../.local/lib/python3.6/site-packages/pysph/base/utils.py:7: in <module>
    from .particle_array import ParticleArray, \
pysph/base/particle_array.pyx:25: in init pysph.base.particle_array
    ???
../.local/lib/python3.6/site-packages/pysph/base/device_helper.py:12: in <module>
    from compyle.template import Template
E   ModuleNotFoundError: No module named 'compyle.template'
_________________________ ERROR collecting parallel/tests/test_openmp.py _________________________
ImportError while importing test module '/home/ehsan/.local/lib/python3.6/site-packages/pysph/parallel/tests/test_openmp.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../.local/lib/python3.6/site-packages/pysph/parallel/tests/test_openmp.py:10: in <module>
    from .example_test_case import ExampleTestCase, get_example_script
../.local/lib/python3.6/site-packages/pysph/parallel/tests/example_test_case.py:9: in <module>
    from pysph.solver.utils import load, get_files
../.local/lib/python3.6/site-packages/pysph/solver/utils.py:13: in <module>
    from pysph.solver.output import load, dump, output_formats  # noqa: 401
../.local/lib/python3.6/site-packages/pysph/solver/output.py:9: in <module>
    from pysph.base.particle_array import ParticleArray
pysph/base/particle_array.pyx:25: in init pysph.base.particle_array
    ???
../.local/lib/python3.6/site-packages/pysph/base/device_helper.py:12: in <module>
    from compyle.template import Template
E   ModuleNotFoundError: No module named 'compyle.template'
______________________ ERROR collecting parallel/tests/test_parallel_run.py ______________________
ImportError while importing test module '/home/ehsan/.local/lib/python3.6/site-packages/pysph/parallel/tests/test_parallel_run.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../.local/lib/python3.6/site-packages/pysph/parallel/tests/test_parallel_run.py:12: in <module>
    from pysph.parallel.tests.example_test_case import ExampleTestCase, get_example_script
../.local/lib/python3.6/site-packages/pysph/parallel/tests/example_test_case.py:9: in <module>
    from pysph.solver.utils import load, get_files
../.local/lib/python3.6/site-packages/pysph/solver/utils.py:13: in <module>
    from pysph.solver.output import load, dump, output_formats  # noqa: 401
../.local/lib/python3.6/site-packages/pysph/solver/output.py:9: in <module>
    from pysph.base.particle_array import ParticleArray
pysph/base/particle_array.pyx:25: in init pysph.base.particle_array
    ???
../.local/lib/python3.6/site-packages/pysph/base/device_helper.py:12: in <module>
    from compyle.template import Template
E   ModuleNotFoundError: No module named 'compyle.template'
_______________________ ERROR collecting solver/tests/test_application.py ________________________
ImportError while importing test module '/home/ehsan/.local/lib/python3.6/site-packages/pysph/solver/tests/test_application.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../.local/lib/python3.6/site-packages/pysph/solver/tests/test_application.py:19: in <module>
    from pysph.solver.application import Application
../.local/lib/python3.6/site-packages/pysph/solver/application.py:18: in <module>
    from pysph.base import utils
../.local/lib/python3.6/site-packages/pysph/base/utils.py:7: in <module>
    from .particle_array import ParticleArray, \
pysph/base/particle_array.pyx:25: in init pysph.base.particle_array
    ???
../.local/lib/python3.6/site-packages/pysph/base/device_helper.py:12: in <module>
    from compyle.template import Template
E   ModuleNotFoundError: No module named 'compyle.template'
__________________________ ERROR collecting solver/tests/test_solver.py __________________________
ImportError while importing test module '/home/ehsan/.local/lib/python3.6/site-packages/pysph/solver/tests/test_solver.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../.local/lib/python3.6/site-packages/pysph/solver/tests/test_solver.py:15: in <module>
    from pysph.solver.solver import Solver
../.local/lib/python3.6/site-packages/pysph/solver/solver.py:12: in <module>
    from pysph.solver.utils import ProgressBar, load, dump
../.local/lib/python3.6/site-packages/pysph/solver/utils.py:13: in <module>
    from pysph.solver.output import load, dump, output_formats  # noqa: 401
../.local/lib/python3.6/site-packages/pysph/solver/output.py:9: in <module>
    from pysph.base.particle_array import ParticleArray
pysph/base/particle_array.pyx:25: in init pysph.base.particle_array
    ???
../.local/lib/python3.6/site-packages/pysph/base/device_helper.py:12: in <module>
    from compyle.template import Template
E   ModuleNotFoundError: No module named 'compyle.template'
_______________________ ERROR collecting solver/tests/test_solver_utils.py _______________________
ImportError while importing test module '/home/ehsan/.local/lib/python3.6/site-packages/pysph/solver/tests/test_solver_utils.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../.local/lib/python3.6/site-packages/pysph/solver/tests/test_solver_utils.py:14: in <module>
    from pysph.base.utils import get_particle_array, get_particle_array_wcsph
../.local/lib/python3.6/site-packages/pysph/base/utils.py:7: in <module>
    from .particle_array import ParticleArray, \
pysph/base/particle_array.pyx:25: in init pysph.base.particle_array
    ???
../.local/lib/python3.6/site-packages/pysph/base/device_helper.py:12: in <module>
    from compyle.template import Template
E   ModuleNotFoundError: No module named 'compyle.template'
___________________ ERROR collecting sph/bc/tests/test_simple_inlet_outlet.py ____________________
ImportError while importing test module '/home/ehsan/.local/lib/python3.6/site-packages/pysph/sph/bc/tests/test_simple_inlet_outlet.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../.local/lib/python3.6/site-packages/pysph/sph/bc/tests/test_simple_inlet_outlet.py:13: in <module>
    from pysph.base.utils import get_particle_array
../.local/lib/python3.6/site-packages/pysph/base/utils.py:7: in <module>
    from .particle_array import ParticleArray, \
pysph/base/particle_array.pyx:25: in init pysph.base.particle_array
    ???
../.local/lib/python3.6/site-packages/pysph/base/device_helper.py:12: in <module>
    from compyle.template import Template
E   ModuleNotFoundError: No module named 'compyle.template'
______________________ ERROR collecting sph/tests/test_acceleration_eval.py ______________________
ImportError while importing test module '/home/ehsan/.local/lib/python3.6/site-packages/pysph/sph/tests/test_acceleration_eval.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../.local/lib/python3.6/site-packages/pysph/sph/tests/test_acceleration_eval.py:13: in <module>
    from pysph.base.utils import get_particle_array
../.local/lib/python3.6/site-packages/pysph/base/utils.py:7: in <module>
    from .particle_array import ParticleArray, \
pysph/base/particle_array.pyx:25: in init pysph.base.particle_array
    ???
../.local/lib/python3.6/site-packages/pysph/base/device_helper.py:12: in <module>
    from compyle.template import Template
E   ModuleNotFoundError: No module named 'compyle.template'
_______________ ERROR collecting sph/tests/test_acceleration_eval_cython_helper.py _______________
ImportError while importing test module '/home/ehsan/.local/lib/python3.6/site-packages/pysph/sph/tests/test_acceleration_eval_cython_helper.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../.local/lib/python3.6/site-packages/pysph/sph/tests/test_acceleration_eval_cython_helper.py:8: in <module>
    from pysph.base.particle_array import ParticleArray
pysph/base/particle_array.pyx:25: in init pysph.base.particle_array
    ???
../.local/lib/python3.6/site-packages/pysph/base/device_helper.py:12: in <module>
    from compyle.template import Template
E   ModuleNotFoundError: No module named 'compyle.template'
_________________________ ERROR collecting sph/tests/test_integrator.py __________________________
ImportError while importing test module '/home/ehsan/.local/lib/python3.6/site-packages/pysph/sph/tests/test_integrator.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../.local/lib/python3.6/site-packages/pysph/sph/tests/test_integrator.py:9: in <module>
    from pysph.base.utils import get_particle_array, get_particle_array_wcsph
../.local/lib/python3.6/site-packages/pysph/base/utils.py:7: in <module>
    from .particle_array import ParticleArray, \
pysph/base/particle_array.pyx:25: in init pysph.base.particle_array
    ???
../.local/lib/python3.6/site-packages/pysph/base/device_helper.py:12: in <module>
    from compyle.template import Template
E   ModuleNotFoundError: No module named 'compyle.template'
__________________ ERROR collecting sph/tests/test_integrator_cython_helper.py ___________________
ImportError while importing test module '/home/ehsan/.local/lib/python3.6/site-packages/pysph/sph/tests/test_integrator_cython_helper.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../.local/lib/python3.6/site-packages/pysph/sph/tests/test_integrator_cython_helper.py:5: in <module>
    from pysph.base.utils import get_particle_array
../.local/lib/python3.6/site-packages/pysph/base/utils.py:7: in <module>
    from .particle_array import ParticleArray, \
pysph/base/particle_array.pyx:25: in init pysph.base.particle_array
    ???
../.local/lib/python3.6/site-packages/pysph/base/device_helper.py:12: in <module>
    from compyle.template import Template
E   ModuleNotFoundError: No module named 'compyle.template'
_______________________ ERROR collecting sph/tests/test_integrator_step.py _______________________
ImportError while importing test module '/home/ehsan/.local/lib/python3.6/site-packages/pysph/sph/tests/test_integrator_step.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../.local/lib/python3.6/site-packages/pysph/sph/tests/test_integrator_step.py:6: in <module>
    from pysph.base.utils import get_particle_array as gpa
../.local/lib/python3.6/site-packages/pysph/base/utils.py:7: in <module>
    from .particle_array import ParticleArray, \
pysph/base/particle_array.pyx:25: in init pysph.base.particle_array
    ???
../.local/lib/python3.6/site-packages/pysph/base/device_helper.py:12: in <module>
    from compyle.template import Template
E   ModuleNotFoundError: No module named 'compyle.template'
_____________________ ERROR collecting sph/tests/test_kernel_corrections.py ______________________
ImportError while importing test module '/home/ehsan/.local/lib/python3.6/site-packages/pysph/sph/tests/test_kernel_corrections.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../.local/lib/python3.6/site-packages/pysph/sph/tests/test_kernel_corrections.py:5: in <module>
    from pysph.base.utils import get_particle_array
../.local/lib/python3.6/site-packages/pysph/base/utils.py:7: in <module>
    from .particle_array import ParticleArray, \
pysph/base/particle_array.pyx:25: in init pysph.base.particle_array
    ???
../.local/lib/python3.6/site-packages/pysph/base/device_helper.py:12: in <module>
    from compyle.template import Template
E   ModuleNotFoundError: No module named 'compyle.template'
___________________ ERROR collecting sph/tests/test_multi_group_integrator.py ____________________
ImportError while importing test module '/home/ehsan/.local/lib/python3.6/site-packages/pysph/sph/tests/test_multi_group_integrator.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../.local/lib/python3.6/site-packages/pysph/sph/tests/test_multi_group_integrator.py:10: in <module>
    from pysph.base.utils import get_particle_array
../.local/lib/python3.6/site-packages/pysph/base/utils.py:7: in <module>
    from .particle_array import ParticleArray, \
pysph/base/particle_array.pyx:25: in init pysph.base.particle_array
    ???
../.local/lib/python3.6/site-packages/pysph/base/device_helper.py:12: in <module>
    from compyle.template import Template
E   ModuleNotFoundError: No module named 'compyle.template'
___________________________ ERROR collecting sph/tests/test_scheme.py ____________________________
ImportError while importing test module '/home/ehsan/.local/lib/python3.6/site-packages/pysph/sph/tests/test_scheme.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../.local/lib/python3.6/site-packages/pysph/sph/tests/test_scheme.py:4: in <module>
    from pysph.sph.wc.edac import EDACScheme
../.local/lib/python3.6/site-packages/pysph/sph/wc/edac.py:22: in <module>
    from pysph.base.utils import get_particle_array
../.local/lib/python3.6/site-packages/pysph/base/utils.py:7: in <module>
    from .particle_array import ParticleArray, \
pysph/base/particle_array.pyx:25: in init pysph.base.particle_array
    ???
../.local/lib/python3.6/site-packages/pysph/base/device_helper.py:12: in <module>
    from compyle.template import Template
E   ModuleNotFoundError: No module named 'compyle.template'
_________________________ ERROR collecting tools/tests/test_geometry.py __________________________
../.local/lib/python3.6/site-packages/pysph/tools/tests/test_geometry.py:5: in <module>
    import pysph.tools.geometry as G
../.local/lib/python3.6/site-packages/pysph/tools/geometry.py:4: in <module>
    from pysph.base.nnps import LinkedListNNPS
../.local/lib/python3.6/site-packages/pysph/base/nnps.py:1: in <module>
    from pysph.base.nnps_base import get_number_of_threads, py_flatten, \
pysph/base/nnps_base.pyx:218: in init pysph.base.nnps_base
    ???
E   AttributeError: type object 'pysph.base.nnps_base.NNPSParticleArrayWrapper' has no attribute '__reduce_cython__'
_______________________ ERROR collecting tools/tests/test_geometry_stl.py ________________________
ImportError while importing test module '/home/ehsan/.local/lib/python3.6/site-packages/pysph/tools/tests/test_geometry_stl.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../.local/lib/python3.6/site-packages/pysph/tools/tests/test_geometry_stl.py:5: in <module>
    from pysph.base.particle_array import ParticleArray
pysph/base/particle_array.pyx:25: in init pysph.base.particle_array
    ???
../.local/lib/python3.6/site-packages/pysph/base/device_helper.py:12: in <module>
    from compyle.template import Template
E   ModuleNotFoundError: No module named 'compyle.template'
_______________________ ERROR collecting tools/tests/test_interpolator.py ________________________
ImportError while importing test module '/home/ehsan/.local/lib/python3.6/site-packages/pysph/tools/tests/test_interpolator.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../.local/lib/python3.6/site-packages/pysph/tools/tests/test_interpolator.py:16: in <module>
    from pysph.tools.interpolator import get_nx_ny_nz, Interpolator
../.local/lib/python3.6/site-packages/pysph/tools/interpolator.py:8: in <module>
    from pysph.base.utils import get_particle_array
../.local/lib/python3.6/site-packages/pysph/base/utils.py:7: in <module>
    from .particle_array import ParticleArray, \
pysph/base/particle_array.pyx:25: in init pysph.base.particle_array
    ???
../.local/lib/python3.6/site-packages/pysph/base/device_helper.py:12: in <module>
    from compyle.template import Template
E   ModuleNotFoundError: No module named 'compyle.template'
_______________________ ERROR collecting tools/tests/test_sph_evaluator.py _______________________
ImportError while importing test module '/home/ehsan/.local/lib/python3.6/site-packages/pysph/tools/tests/test_sph_evaluator.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../.local/lib/python3.6/site-packages/pysph/tools/tests/test_sph_evaluator.py:5: in <module>
    from pysph.base.utils import get_particle_array
../.local/lib/python3.6/site-packages/pysph/base/utils.py:7: in <module>
    from .particle_array import ParticleArray, \
pysph/base/particle_array.pyx:25: in init pysph.base.particle_array
    ???
../.local/lib/python3.6/site-packages/pysph/base/device_helper.py:12: in <module>
    from compyle.template import Template
E   ModuleNotFoundError: No module named 'compyle.template'
======================================== warnings summary ========================================
/home/ehsan/.local/lib/python3.6/site-packages/compyle/ext_module.py:7
  /home/ehsan/.local/lib/python3.6/site-packages/compyle/ext_module.py:7: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

/home/ehsan/.local/lib/python3.6/site-packages/pysph/examples/tests/test_examples.py:84
  /home/ehsan/.local/lib/python3.6/site-packages/pysph/examples/tests/test_examples.py:84: PytestUnknownMarkWarning: Unknown pytest.mark.slow - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
    @mark.slow

/home/ehsan/.local/lib/python3.6/site-packages/pysph/parallel/tests/test_parallel.py:51
  /home/ehsan/.local/lib/python3.6/site-packages/pysph/parallel/tests/test_parallel.py:51: PytestUnknownMarkWarning: Unknown pytest.mark.parallel - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
    @mark.parallel

/home/ehsan/.local/lib/python3.6/site-packages/pysph/parallel/tests/test_parallel.py:55
  /home/ehsan/.local/lib/python3.6/site-packages/pysph/parallel/tests/test_parallel.py:55: PytestUnknownMarkWarning: Unknown pytest.mark.parallel - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
    @mark.parallel

/home/ehsan/.local/lib/python3.6/site-packages/pysph/parallel/tests/test_parallel.py:68
  /home/ehsan/.local/lib/python3.6/site-packages/pysph/parallel/tests/test_parallel.py:68: PytestUnknownMarkWarning: Unknown pytest.mark.slow - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
    @mark.slow

/home/ehsan/.local/lib/python3.6/site-packages/pysph/parallel/tests/test_parallel.py:69
  /home/ehsan/.local/lib/python3.6/site-packages/pysph/parallel/tests/test_parallel.py:69: PytestUnknownMarkWarning: Unknown pytest.mark.parallel - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
    @mark.parallel

/home/ehsan/.local/lib/python3.6/site-packages/pysph/parallel/tests/test_parallel.py:88
  /home/ehsan/.local/lib/python3.6/site-packages/pysph/parallel/tests/test_parallel.py:88: PytestUnknownMarkWarning: Unknown pytest.mark.parallel - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
    @mark.parallel

/home/ehsan/.local/lib/python3.6/site-packages/pysph/parallel/tests/test_parallel.py:94
  /home/ehsan/.local/lib/python3.6/site-packages/pysph/parallel/tests/test_parallel.py:94: PytestUnknownMarkWarning: Unknown pytest.mark.parallel - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
    @mark.parallel

/home/ehsan/.local/lib/python3.6/site-packages/pysph/parallel/tests/test_parallel.py:108
  /home/ehsan/.local/lib/python3.6/site-packages/pysph/parallel/tests/test_parallel.py:108: PytestUnknownMarkWarning: Unknown pytest.mark.parallel - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
    @mark.parallel

-- Docs: https://docs.pytest.org/en/latest/warnings.html
==================================== short test summary info =====================================
ERROR base/tests/test_device_helper.py
ERROR base/tests/test_domain_manager.py
ERROR base/tests/test_neighbor_cache.py - AttributeError: type object 'pysph.base.nnps_base.NNP...
ERROR base/tests/test_nnps.py
ERROR base/tests/test_octree.py
ERROR base/tests/test_particle_array.py
ERROR base/tests/test_periodic_nnps.py - AttributeError: type object 'pysph.base.nnps_base.NNPS...
ERROR base/tests/test_utils.py
ERROR parallel/tests/test_openmp.py
ERROR parallel/tests/test_parallel_run.py
ERROR solver/tests/test_application.py
ERROR solver/tests/test_solver.py
ERROR solver/tests/test_solver_utils.py
ERROR sph/bc/tests/test_simple_inlet_outlet.py
ERROR sph/tests/test_acceleration_eval.py
ERROR sph/tests/test_acceleration_eval_cython_helper.py
ERROR sph/tests/test_integrator.py
ERROR sph/tests/test_integrator_cython_helper.py
ERROR sph/tests/test_integrator_step.py
ERROR sph/tests/test_kernel_corrections.py
ERROR sph/tests/test_multi_group_integrator.py
ERROR sph/tests/test_scheme.py
ERROR tools/tests/test_geometry.py - AttributeError: type object 'pysph.base.nnps_base.NNPSPart...
ERROR tools/tests/test_geometry_stl.py
ERROR tools/tests/test_interpolator.py
ERROR tools/tests/test_sph_evaluator.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 26 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================= 9 warnings, 26 errors in 1.45s =================================`

**Comment by prabhuramachandran** [comment]
Sorry, right now you will need to install the latest version of compyle from github, if you do not have the repository cloned you can also do this:
```
pip install https://github.com/pypr/compyle/zipball/master
```
Once we push a new compyle release this should not be needed but at the moment we haven't yet pushed a new release.  Closing this for now.
