### ISSUE TITLE
OSError: [WinError 6] invalid handle

### ISSUE THREAD

**Issue by DaYongUpUp** [pypr/pysph#268]
PySPH installed with Python3.7 in Anaconda environment.
When all libs installed and running the examples, raise error:
OSError: [WinError 6] invalid handle
What is the problem?

I installed PySPH with "pip install PySPH", after the error raised, I tried with "pip install https://github.com/pypr/compyle/zipball/master", and the problem was still there.

**Comment by prabhuramachandran** [comment]
Can you install pysph from master and try. Please also post the full error message you are getting? i.e.
```
pip install https://github.com/pypr/pysph/zipball/master
```

**Comment by DaYongUpUp** [comment]
> Can you install pysph from master and try. Please also post the full error message you are getting? i.e.
> 
> ```
> pip install https://github.com/pypr/pysph/zipball/master
> ```

I tried installing and uninstalling with some times, main step is as following steps:

0. I uninstalled the PySPH lib;
1. I installed PySPH with "pip install https://github.com/pypr/pysph/zipball/master" and got some errors in the building process like this "Building wheel for PySPH (setup.py) ... error" and followed with hundreds of line of error information, most of error is "Error compiling Cython file".  The information ended with a line like this "ERROR: Failed building wheel for PySPH", and followed with "Running setup.py clean for PySPH" and Successfully installed PySPH-1.-b1.dev0. and there was still OSError [WinError 6].
2. I uninstalled PySPH again and reinstall with "pip install https://github.com/pypr/pysph/zipball/master" and installed successfully and the building error also disapear, but when running the example cavity, it failed with warnings and errors like below:
`cl: 命令行 warning D9024 :无法识别的源文件类型“Files”，假定为对象文件
cl: 命令行 warning D9027 :源文件“Files”被忽略
cl: 命令行 warning D9024 :无法识别的源文件类型“(x86)\Microsoft”，假定为对象文件
cl: 命令行 warning D9027 :源文件“(x86)\Microsoft”被忽略
cl: 命令行 warning D9024 :无法识别的源文件类型“Visual”，假定为对象文件
cl: 命令行 warning D9027 :源文件“Visual”被忽略
cl: 命令行 warning D9024 :无法识别的源文件类型“Studio”，假定为对象文件
cl: 命令行 warning D9027 :源文件“Studio”被忽略
cl: 命令行 warning D9024 :无法识别的源文件类型“14.0\VC\BIN\x86_amd64\cl.exe”，假定为对象文件
cl: 命令行 warning D9027 :源文件“14.0\VC\BIN\x86_amd64\cl.exe”被忽略
cl: 命令行 warning D9024 :无法识别的源文件类型“Files”，假定为对象文件
cl: 命令行 warning D9027 :源文件“Files”被忽略
cl: 命令行 warning D9024 :无法识别的源文件类型“(x86)\Microsoft”，假定为对象文件
cl: 命令行 warning D9027 :源文件“(x86)\Microsoft”被忽略
cl: 命令行 warning D9024 :无法识别的源文件类型“Visual”，假定为对象文件
cl: 命令行 warning D9027 :源文件“Visual”被忽略
cl: 命令行 warning D9024 :无法识别的源文件类型“Studio”，假定为对象文件
cl: 命令行 warning D9027 :源文件“Studio”被忽略
cl: 命令行 warning D9024 :无法识别的源文件类型“14.0\VC\INCLUDE”，假定为对象文件
cl: 命令行 warning D9027 :源文件“14.0\VC\INCLUDE”被忽略
cl: 命令行 warning D9024 :无法识别的源文件类型“Files”，假定为对象文件
cl: 命令行 warning D9027 :源文件“Files”被忽略
cl: 命令行 warning D9024 :无法识别的源文件类型“(x86)\Microsoft”，假定为对象文件
cl: 命令行 warning D9027 :源文件“(x86)\Microsoft”被忽略
cl: 命令行 warning D9024 :无法识别的源文件类型“Visual”，假定为对象文件
cl: 命令行 warning D9027 :源文件“Visual”被忽略
cl: 命令行 warning D9024 :无法识别的源文件类型“Studio”，假定为对象文件
cl: 命令行 warning D9027 :源文件“Studio”被忽略
cl: 命令行 warning D9024 :无法识别的源文件类型“14.0\VC\ATLMFC\INCLUDE”，假定为对象文件
cl: 命令行 warning D9027 :源文件“14.0\VC\ATLMFC\INCLUDE”被忽略
cl: 命令行 warning D9024 :无法识别的源文件类型“Files”，假定为对象文件
cl: 命令行 warning D9027 :源文件“Files”被忽略
cl: 命令行 warning D9024 :无法识别的源文件类型“(x86)\Windows”，假定为对象文件
cl: 命令行 warning D9027 :源文件“(x86)\Windows”被忽略
cl: 命令行 warning D9024 :无法识别的源文件类型“Kits\10\include\10.0.10240.0\ucrt”，假定为对象文件
cl: 命令行 warning D9027 :源文件“Kits\10\include\10.0.10240.0\ucrt”被忽略
cl: 命令行 warning D9024 :无法识别的源文件类型“Files”，假定为对象文件
cl: 命令行 warning D9027 :源文件“Files”被忽略
cl: 命令行 warning D9024 :无法识别的源文件类型“(x86)\Windows”，假定为对象文件
cl: 命令行 warning D9027 :源文件“(x86)\Windows”被忽略
cl: 命令行 warning D9024 :无法识别的源文件类型“Kits\NETFXSDK\4.6.1\include\um”，假定为对象文件
cl: 命令行 warning D9027 :源文件“Kits\NETFXSDK\4.6.1\include\um”被忽略
cl: 命令行 warning D9024 :无法识别的源文件类型“Files”，假定为对象文件
cl: 命令行 warning D9027 :源文件“Files”被忽略
cl: 命令行 warning D9024 :无法识别的源文件类型“(x86)\Windows”，假定为对象文件
cl: 命令行 warning D9027 :源文件“(x86)\Windows”被忽略
cl: 命令行 warning D9024 :无法识别的源文件类型“Kits\8.1\include\\shared”，假定为对象文件
cl: 命令行 warning D9027 :源文件“Kits\8.1\include\\shared”被忽略
cl: 命令行 warning D9024 :无法识别的源文件类型“Files”，假定为对象文件
cl: 命令行 warning D9027 :源文件“Files”被忽略
cl: 命令行 warning D9024 :无法识别的源文件类型“(x86)\Windows”，假定为对象文件
cl: 命令行 warning D9027 :源文件“(x86)\Windows”被忽略
cl: 命令行 warning D9024 :无法识别的源文件类型“Kits\8.1\include\\um”，假定为对象文件
cl: 命令行 warning D9027 :源文件“Kits\8.1\include\\um”被忽略
cl: 命令行 warning D9024 :无法识别的源文件类型“Files”，假定为对象文件
cl: 命令行 warning D9027 :源文件“Files”被忽略
cl: 命令行 warning D9024 :无法识别的源文件类型“(x86)\Windows”，假定为对象文件
cl: 命令行 warning D9027 :源文件“(x86)\Windows”被忽略
cl: 命令行 warning D9024 :无法识别的源文件类型“Kits\8.1\include\\winrt”，假定为对象文件
cl: 命令行 warning D9027 :源文件“Kits\8.1\include\\winrt”被忽略
cl: 命令行 warning D9024 :无法识别的源文件类型“Files”，假定为对象文件
cl: 命令行 warning D9027 :源文件“Files”被忽略
cl: 命令行 warning D9024 :无法识别的源文件类型“(x86)\IntelSWTools\Trace”，假定为对象文件
cl: 命令行 warning D9027 :源文件“(x86)\IntelSWTools\Trace”被忽略
cl: 命令行 warning D9024 :无法识别的源文件类型“Analyzer”，假定为对象文件
cl: 命令行 warning D9027 :源文件“Analyzer”被忽略
cl: 命令行 warning D9024 :无法识别的源文件类型“and”，假定为对象文件
cl: 命令行 warning D9027 :源文件“and”被忽略
cl: 命令行 warning D9024 :无法识别的源文件类型“Collector\9.1.1.019\include”，假定为对象文件
cl: 命令行 warning D9027 :源文件“Collector\9.1.1.019\include”被忽略
m_f06d9e7a48e18d985cef8a37a909393b.cpp
d:\apps\anaconda3\envs\pysph\include\pyconfig.h(59): fatal error C1083: 无法打开包括文件: “io.h”: No such file or directory such file or directory
********************************************************************************
ERROR
********************************************************************************
Compilation of code failed, please check error messages above.`

Thank fou for your time.

**Comment by prabhuramachandran** [comment]
You should always install compyle first and then pysph.  Also the entire log file is not relevant only the last line is and I do not understand the language. Anyway, for some reason it is unable to find the header file io.h which leads me to this: https://stackoverflow.com/questions/40018405/cannot-open-include-file-io-h-no-such-file-or-directory
There are many possible configuration problems unfortunately.
Did you follow this: https://pysph.readthedocs.io/en/latest/installation.html#installing-visual-c-compiler-for-python ?  
Let me know if there is more information that is needed in the documentation.

**Comment by DaYongUpUp** [comment]
> You should always install compyle first and then pysph. Also the entire log file is not relevant only the last line is and I do not understand the language. Anyway, for some reason it is unable to find the header file io.h which leads me to this: https://stackoverflow.com/questions/40018405/cannot-open-include-file-io-h-no-such-file-or-directory
> There are many possible configuration problems unfortunately.
> Did you follow this: https://pysph.readthedocs.io/en/latest/installation.html#installing-visual-c-compiler-for-python ?
> Let me know if there is more information that is needed in the documentation.

Thank you, I reinstalled associated libs and the example can run, except the "io.h" is still can not be located even i add the path of the io.h of VS to the environment. I will figure it out.
Thank you for your time again.
