### ISSUE TITLE
ModuleNotFoundError: No module named 'pysph.base.gpu_nnps_base'

### ISSUE THREAD

**Issue by ckesanapalli** [pypr/pysph#273]
Hi Guys, 

When I am running dam_break_2d example (https://github.com/pypr/pysph/blob/master/pysph/examples/dam_break_2d.py) using OpenCL, I am getting the following error

`python dam_break_2d.py --opencl`

Error
```python
Traceback (most recent call last):
  File "dam_break_2d.py", line 303, in <module>
    app.run()
  File "C:\Users\CKesanapalli\Anaconda3\lib\site-packages\pysph\solver\application.py", line 1569, in run  
    self._configure_solver()
  File "C:\Users\CKesanapalli\Anaconda3\lib\site-packages\pysph\solver\application.py", line 1025, in _configure_solver
    from pysph.base.gpu_nnps import ZOrderGPUNNPS
  File "C:\Users\CKesanapalli\Anaconda3\lib\site-packages\pysph\base\gpu_nnps.py", line 1, in <module>     
    from pysph.base.gpu_nnps_base import GPUNeighborCache, GPUNNPS, BruteForceNNPS
ModuleNotFoundError: No module named 'pysph.base.gpu_nnps_base'
```
The error is directing to this line. 
https://github.com/pypr/pysph/blob/7402819cfa8ec28031851e2cdfba6a7544e05bd9/pysph/base/gpu_nnps.py#L1

Can you tell me how to resolve this issue

Thank you

**Comment by prabhuramachandran** [comment]
If you have a GPU you need to install pysph once the required GPU libraries are available, some parts of PySPH are compiled only if PyOpenCL is available.  Right now you cannot install pysph without setting up the GPU libraries and then install the GPU libraries (say pyopencl) and expect for pysph to work with it.  Just reinstall PySPH.  We may change this in the future but not right now.

**Comment by ckesanapalli** [comment]
I reinstalled the PySPH library but I am getting same error. 

```python
Traceback (most recent call last):
  File "dam_break_2d.py", line 303, in <module>
    app.run()
  File "C:\Users\CKesanapalli\Anaconda3\lib\site-packages\pysph\solver\application.py", line 1569, in run  
    self._configure_solver()
  File "C:\Users\CKesanapalli\Anaconda3\lib\site-packages\pysph\solver\application.py", line 1025, in _configure_solver
    from pysph.base.gpu_nnps import ZOrderGPUNNPS
  File "C:\Users\CKesanapalli\Anaconda3\lib\site-packages\pysph\base\gpu_nnps.py", line 1, in <module>     
    from pysph.base.gpu_nnps_base import GPUNeighborCache, GPUNNPS, BruteForceNNPS
ModuleNotFoundError: No module named 'pysph.base.gpu_nnps_base'
```

**Comment by prabhuramachandran** [comment]
Are you sure?  Can you pip uninstall and then reinstall?  Also, if you are likely to use the latest pysph always then it may be easier to use `python setup.py develop` that way you don't need to uninstall and reinstall.  How exactly did you install this?  If you did `pip install` then pip caches the wheels it installs.  Please provide more details.

**Comment by prabhuramachandran** [comment]
Also for tiny problems using a GPU will likely be very slow.  You need many particles, just having more timesteps for longer runs will not help at all.  3D usually works better and I will warn you that opencl support is not 100% like the CPU backend.

**Comment by ckesanapalli** [comment]
I Finally resolved the issue after developing the code after install pyopencl
```bash
pip uninstall pysph
pip install pyopencl
pip install -r requirements.txt
python setup.py develop
```
> Also for tiny problems using a GPU will likely be very slow.

It is true. I ran for the dam_break_2d case with 3838 particles and run times are 
**OpenMP** : (It runs fast but somehow the simulation is terminating at 38%)
**CPU OpenCL** : 1730.77281 secs
**GPU OpenCL** : 878.56608 secs
