### ISSUE TITLE
Can PySPH achieve DEM-SPH coupling? And if it can , how to do it ?

### ISSUE THREAD

**Issue by 11-27** [pypr/pysph#282]
I really admire your work. It's so amazing！
I want ask, Can PySPH achieve DEM-SPH coupling? And if it can , how to do it ?

**Comment by dineshadepu** [comment]
Hey,

Thanks for the compliment, all praise to @prabhuramachandran. I work on DEM in PySPH. I have implemented DEM in my local branch, it needs a little more validation. You can expect coupling with SPH in a couple of months with relevant examples.  

I will keep you posted when it is ready.

**Comment by 11-27** [comment]
Dear:
Really? Amazing！！！I'm very happy！
I want to do a simulation of gradually adding water to a ball mill.Furthermore, I want to realize the DEM ball of ice and rock in the process of movement, the ice ball melts to produce water. Heat and mass transfer！
Feng

**Comment by prabhuramachandran** [comment]
Thanks for the kind comments.  Thanks @dineshadepu for the answer.  
I think all the contributors deserve the credit.  In any case, there are a few simplistic DEM models in the rigid_body module (https://github.com/pypr/pysph/blob/master/pysph/sph/rigid_body.py) although this is certainly not enough, it does show you in principle how things can be done.  I am closing this issue at this point though.
