### ISSUE TITLE
Question during view with  s00,s01

### ISSUE THREAD

**Issue by CuiBinghui91** [pypr/pysph#291]
HI,
I have a confused with the view of s00 or s01..., when using the VonMisesPlasticity2D. The value of s00 or s01 is greater than the flow_stress(Yo).
![1](https://user-images.githubusercontent.com/58969008/99023713-1effae80-25a0-11eb-8ad8-84b426ad8fad.png)

Best,
Binghui

**Comment by prabhuramachandran** [comment]
This is not a bug, basically the solver dumps output files after the integrator has completed a time step. The accelerations are very high and so the values of s00 etc. are all large. The first group of equations will then limit the stresses as per the von Mises yield criterion before the stresses are used again.
