### ISSUE TITLE
Guide on readthedocs provide errors with Python 3

### ISSUE THREAD

**Issue by quang-ha** [pypr/pysph#3]
In the section http://pysph.readthedocs.io/en/latest/tutorial/circular_patch_simple.html#interpolating-properties, the following code will fail in Python 3:

```
interp = Interpolator(parrays.values(), num_points=10000)
p = interp.interpolate('p')
```

Simply because in Python 3, `dict.values` return only a view of dict. If `pysph` is installed with Python 3.x, a solution to fix is:

```
interp = Interpolator(list(parrays.values()), num_points=10000)
p = interp.interpolate('p')
```

This makes me wonder whether it would be better to stick with one Python version only (at the time of speaking Python 3 is the future so debateably it would be better to stick with them).

**Comment by prabhuramachandran** [comment]
I've addressed this in PR #5.  There are still too many people using 2.7 for me to not want to switch entirely to 3.x  The docs predate the switch to 2.7.  Please let us know if there are other issues or better yet, send us a PR.  Thanks.
