### ISSUE TITLE
Probably a bug in sisph

### ISSUE THREAD

**Issue by sahil-ramagiri** [pypr/pysph#309]
https://github.com/pypr/pysph/blob/bc5c793a82cb4a1f57a7602aea1be85d5e4cc87f/pysph/sph/isph/sisph.py#L152-L155

The MomentumEquationArtificialViscosity Equation is first evaluated and the calculated accelerations are thrown away in MomentumEquationBodyForce, or am I missing something.

**Comment by abhinavmuta** [comment]
The `initialize` method of all the classes that are Grouped together are run at once, see here for more info https://pysph.readthedocs.io/en/latest/design/equations.html?highlight=group#understanding-groups-a-bit-more.
The `MomentumEquationArtificialViscosity` is grouped with `LaminarViscosity`, `MomentumEquationBodyForce` and others. So, the initialize method of all these equations are run in the same for loop, which is over all the `destination` particles.
