### ISSUE TITLE
No traitsui.toolkits plugin could be loaded for qt4

### ISSUE THREAD

**Issue by qwerdf4** [pypr/pysph#312]
No traitsui.toolkits plugin could be loaded for qt4

**Comment by chhu** [comment]
Haha, just had the same experience from a fresh pip3 install. For me this solved the issue:
`pip3 install pyqt5`

**Comment by adi18997** [comment]
> Haha, just had the same experience from a fresh pip3 install. For me this solved the issue:
> `pip3 install pyqt5`

I am not able to see output just white screen after the code

**Comment by JeanLeu** [comment]
Hi, I met the same error "RuntimeError: No traitsui.toolkits plugin could be loaded for qt4". I tried to pip install pyqt5, but it didn't work. Do you have any idea?

**Comment by cassiez2233** [comment]
> Hi, I met the same error "RuntimeError: No traitsui.toolkits plugin could be loaded for qt4". I tried to pip install pyqt5, but it didn't work. Do you have any idea?

hello, have you solved this problem? I met the same one.

**Comment by JeanLeu** [comment]
> > Hi, I met the same error "RuntimeError: No traitsui.toolkits plugin could be loaded for qt4". I tried to pip install pyqt5, but it didn't work. Do you have any idea?
> 
> hello, have you solved this problem? I met the same one.

No, I still have these problem.

**Comment by cassiez2233** [comment]
> 

Can I ensure some questions?
Did you use pyinstaller to pack the exe?
when you packed it, was there some warnings like: "lib not found in folders like ‘pyqt’"？
I want to know if the error of "RuntimeError: No traitsui.toolkits plugin could be loaded for qt4" is related to the dependency of dll in pyqt folders.

**Comment by harshn05** [comment]
Any resolution to the issue?

**Comment by prabhuramachandran** [comment]
You need to install pyqt5 or pyside2 or pyside6; a compatible UI toolkit should resolve the issue. Otherwise dump VTK files using `pysph dump_vtk` and load it up with ParaView.  Alternatively, use `pysph binder` and use the created notebook (this is quite limited but should let you at least view the data). This is really not a pysph issue per-se but more a Mayavi one so closing.
