### ISSUE TITLE
Facing error while running dam_break_3d 

### ISSUE THREAD

**Issue by adi18997** [pypr/pysph#324]
if __name__ == '__main__':
    app = DamBreak3D()
    app.run()
    app.post_process(app.info_filename)
zsh: parse error near `sd,'

Whenever I am trying to run the code I see this error. I don't know how to solve

**Comment by prabhuramachandran** [comment]
This is not a bug, please only file issues that are issues.  In this case, you are cut pasting the code into a terminal and not saving the file and executing it with Python. If you have questions please send an email to the pysph-users google group.
