### ISSUE TITLE
cull_factor is not initialized in code

### ISSUE THREAD

**Issue by TermeHansen** [pypr/pysph#352]
cull_factor is not initialized in all cases here

https://github.com/pypr/pysph/blob/bc5c793a82cb4a1f57a7602aea1be85d5e4cc87f/pysph/tools/ipy_viewer.py#L242

and make code crash if not set when reaching this line
https://github.com/pypr/pysph/blob/bc5c793a82cb4a1f57a7602aea1be85d5e4cc87f/pysph/tools/ipy_viewer.py#L372

**Comment by prabhuramachandran** [comment]
Thanks, I fixed this.
