### ISSUE TITLE
how to use TVF wall boundary for solid 

### ISSUE THREAD

**Issue by lililii124** [pypr/pysph#389]
Hello, pysph code maintainer, I want to build a solid mechanics example of uniaxial stretching of a round rod, but I found that pysph does not have a function to apply fixed velocity boundary conditions, so I want to use the wall method to apply tension, but Can functions such as setWallVelocity in TVF be used simultaneously when using equations in other parts, such as solid_mech.basic? I added relevant properties to the widget with wall property (add_properties(pa, 'wg','wij','ug','vg','uf','vf','wf')
) but still get an error. If you are free, I sincerely hope to get your answer
![Quicker_20231128_225202](https://github.com/pypr/pysph/assets/64952090/9a442a29-e070-4459-a84a-6e7ba991e3d2)

**Comment by lililii124** [comment]
![Quicker_20231128_225202](https://github.com/pypr/pysph/assets/64952090/a1f7f6c0-f170-40e4-ae03-91881c08cce4)
I solved it, thank you! Just a random question, will pysph implement the rkpm method?

**Comment by Zarathustra98** [comment]
@lililii124 Hey how do you set up the example? Do you mind sharing your case?
